version: 2.1

orbs:
  python: circleci/python@0.2.1
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: install deps
          command: make install
      - python/load-cache
      # - python/install-deps
      - python/save-cache
      - run:
          command: make test #./manage.py test
          name: Test
      - codecov/upload:
          file: "coverage.xml"

workflows:
  main:
    jobs:
      - build-and-test
